print("Welcome to the Investigation Game.")
print("Your job is to find out who stole the bar of gold from the house.")
print("Here are the people who were at the house at the time:")
print("The Mum, the child, the window cleaner and the plumber.")
print("GOOD LUCK")
print("You here a scream and sprint up to your the Mum's bedroom. You ask her what is wrong.\nShe tell you that her bar of gold has been stolen. You assure her that you will find it, and sprint off around the house.")
print("You notice the window cleaner looking very guilty outside. You run over to him and ask him what is wrong. He threatens you with his mop.")
print("You can either:")
print("1) Run away")
print("2) Stand your ground")
playerChoice = input()
if playerChoice == '1':
  print("You sprint off and over to the window cleaner's ladder.\nYou can either:")
  print("1) Climb the ladder, onto the roof")
  print("2) Run over to the front door and into the house")
  playerChoice = input()
  if playerChoice == '1':
    print("You clamber up the roof to find...THE BAR OF GOLD! You spin round to find the window cleaner looking very guilty and annoyed. He explains to you that the plumber had made a whole on the pipes, so when the Mum went into the bathroom, the water wasn't working.\nThis was a distraction. Then the window cleaner climbed through the Mum's bedroom window, and stole the bar of gold to hide it on the roof during all the chaos.")
    print("Then you notice that the police are there and have already got the plumber handcuffed-The Mum must have called them.")